---
abstract: 'simple way to turn URIs into QNames'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords:
  - Namespace
  - Namespaces
  - Prefix
  - Prefixes
  - RDF
  - xmlns
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::Prefixes
name: RDF-Prefixes
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-Prefixes
  homepage: https://metacpan.org/release/RDF-Prefixes
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-rdf-prefixes
version: 0.003
